FROM golang:1.16
RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

WORKDIR /opt/
RUN git clone https://github.com/jonathanschmittblog/jsapi-websocket.git
WORKDIR /opt/jsapi-websocket
RUN go get
RUN go build jsapi-websocket

CMD ["air"]