FROM golang:1.16 as base

FROM base as dev

RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

WORKDIR /opt/app/tests
CMD ["air"]

ENTRYPOINT ["go", "test", "-v", "./...", "-coverprofile", "cover.out"]